version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080" # Adjust port mapping as needed
    environment:
      MYSQL_HOST: db
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
    depends_on:
      - db
    entrypoint: ["/app/MrrCalc"]
    command: ["--currency", "USD", "--period", "5", "--input", "/app/subscriptions.json"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"] # Replace with appropriate health check for your app
      interval: 30s
      timeout: 10s
      retries: 5

  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: root
      MYSQL_PASSWORD: rootpassword
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
