name: Go Lint
permissions:
  contents: read
env:
  DEFAULT_GO_VERSION: '1.22'

on:
  pull_request:
    branches:
      - main
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.DEFAULT_GO_VERSION }}

      - name: Install golangci-lint
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.50.1

      - name: Set GOROOT
        run: echo "GOROOT=$(go env GOROOT)" >> $GITHUB_ENV

      - name: Run lint
        run: make lint
        env:
          GOROOT: /opt/hostedtoolcache/go/1.22.4/x64