name: Go Lint and Static Analysis
permissions:
  contents: read
env:
  DEFAULT_GO_VERSION: '1.22'

on:
  pull_request:
    branches:
      - main
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.DEFAULT_GO_VERSION }}

      - name: Install golangci-lint and staticcheck
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.50.1
          go install honnef.co/go/tools/cmd/staticcheck@latest

      - name: Run lint
        run: |
          make lint